logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
  jpa:
    show-sql: true

jwt:
  secret: random-jwt-secret
  duration: 3600000

springdoc:
  swagger-ui:
    path: /docs